#!/usr/bin/env python3
"""Regenerate tickets/BOARD.md from ticket frontmatter."""
import pathlib, re, collections

ROOT = pathlib.Path(__file__).parent
ORDER = ["doing", "blocked", "todo", "done"]
HEAD = {"doing": "In progress", "blocked": "Blocked", "todo": "To do", "done": "Done"}


def parse(path):
    text = path.read_text(encoding="utf-8")
    match = re.match(r"^---\n(.*?)\n---", text, re.S)
    if not match:
        return None
    meta = {}
    for line in match.group(1).splitlines():
        if ":" in line:
            key, _, value = line.partition(":")
            meta[key.strip()] = value.strip().strip('"')
    meta["path"] = path.relative_to(ROOT).as_posix()
    return meta


tickets = [
    meta
    for path in sorted(ROOT.glob("*/*.md"))
    if not path.name.startswith("_")
    for meta in [parse(path)]
    if meta
]

by_status = collections.defaultdict(list)
for ticket in tickets:
    by_status[ticket.get("status", "todo")].append(ticket)

done = len(by_status["done"])
lines = [
    "# Board",
    "",
    f"_Generated by `python3 tickets/board.py` — {done}/{len(tickets)} done._",
    "",
]

for status in ORDER:
    rows = by_status.get(status, [])
    if not rows:
        continue
    lines += [f"## {HEAD[status]} ({len(rows)})", ""]
    lines += ["| Id | Title | Epic | Size | Blocked by |", "|---|---|---|---|---|"]
    for ticket in sorted(rows, key=lambda t: t.get("id", "")):
        blocked = ticket.get("depends_on", "[]").strip("[]") or "—"
        lines.append(
            f"| [{ticket.get('id','?')}]({ticket['path']}) | {ticket.get('title','')} "
            f"| {ticket.get('epic','')} | {ticket.get('size','')} | {blocked} |"
        )
    lines.append("")

(ROOT / "BOARD.md").write_text("\n".join(lines), encoding="utf-8")
print(f"{len(tickets)} tickets → BOARD.md")
